<style type="text/css">
    section .features-row {
        padding: 60px 0 30px 0;
    }
    section .advanced-feature-img-left {
        max-width: 100%;
        float: left;
        padding: 0 30px 30px 0;
    }
    input[type="submit"] {
        border: 1px solid #1dcaca;
        background: #1dde9c;
        color: #fff;
        cursor: pointer;
    }
    input[type="text"] {
        border: 1px solid #1dcdc3;
        margin: 5px 0;
        padding: 5px 10px;
        width: 400px;
    }
</style>

<!--==========================
  Header
============================-->
<header id="header" class="header-fixed">
    <div class="container">

        <div id="logo" class="pull-left">
            <h1><a href="/#intro" class="scrollto">PAW</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="#intro"><img src="img/logo.png" alt="" title="" /></img></a> -->
        </div>

        <nav id="nav-menu-container">
            <ul class="nav-menu">
                <li class="menu-active"><a href="/#intro">Home</a></li>
                <li><a href="/#about">About PAW</a></li>
                <li><a href="/#features">Features</a></li>
                <li><a href="/#benefits">Benefits</a></li>
                <li><a href="https://wallet.paw.digital">Online Wallet</a></li>
                <li><a href="https://tracker.paw.digital">Tracker</a></li>
                <li><a href="https://tribes.paw.digital">Tribes</a></li>
                <li><a href="https://paw.digital/PAW_Whitepawper.pdf" target="_blank">WhitePAWper</a></li>
            </ul>
        </nav><!-- #nav-menu-container -->
    </div>
</header><!-- #header -->


<!--==========================
  Intro Section
============================-->
<section id="intro">

    <div class="intro-text">
        <h2>PAW Distribution</h2>
        <p>Receive PAWs for sending PAWs.</p>
        <img src="img/paw-chest.png" width="250px" alt="" data-aos="fade-left">
        <a href="#distribution-form" class="btn-get-started scrollto">Get PAWs</a>
    </div>

    <div class="product-screens">


    </div>

</section><!-- #intro -->

<main id="main">

    <section id="distribution-form">
        <div class="features-row">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <img class="advanced-feature-img-left" src="img/paw.svg" width="250px" alt="" data-aos="fade-left" />
                        <div data-aos="fade-right">
                            <h2>PAW Distribution</h2>
                            <h3>Send PAW to someone and receive a reward</h3>
                            <div style="display: inline-block;">
                                <form action="/email#distribution-form" method="post">
                                    <input type="hidden" name="action" value="send" />
                                    <input type="text" name="email" value="<?= isset($_POST['email']) ? htmlspecialchars($_POST['email']) : '' ?>" placeholder="john@email.com" /><br />
                                    <input type="text" name="paw_address" value="<?= isset($_POST['paw_address']) ? htmlspecialchars($_POST['paw_address']) : '' ?>" placeholder="Your paw_address" /><br />
                                    <input type="text" name="paw_reward_key" value="<?= isset($_POST['paw_reward_key']) ? htmlspecialchars($_POST['paw_reward_key']) : '' ?>" placeholder="PAW Reward KEY" /><br />
                                    <input type="checkbox" name="terms" value="" <?= isset($_POST['terms']) ?'checked="checked"' : '' ?>/> I vouch that the person I send PAW is not a bot and will not abuse the system.<br /><br />
                                    <input type="submit" value="Send PAW" />
                                </form>
                                <div style="color: #19adb3; font-weight: bold;"><?php echo $sendResult; echo $err ? '<span>'.$err.'</span>' : ''; ?></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="distribution-limits">
        <div class="features-row section-bg">
            <div class="container">
                <div class="row">
                    <div data-aos="fade-right">
                        <h3>PAW Distribution Notes</h3>
                        <p>Only invite who you trust not to be a bot or use a bot on PAW!</p>
                        <p>Sending PAW to people that get flagged can result in a suspension of your own rewarding.</p>
                        <p>The receiver must pick up their PAW for you to receive your reward.</p>
                        <p>Receiver can only be invited once.</p>
                        <p>Maximum 1 invite every 10 minutes.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <? /*
		<section id="distribution-list">
		  <div class="features-row">
				<div class="container">
				  <div class="row">
					<div data-aos="fade-left">
						<h3>Previous Distributions</h3>
					</div>
				</div>
			  </div>
		  </div>
		</section>*/ ?>
</main>